### ISSUE TITLE
Reproduce the results from the RDF2Vec paper

### ISSUE THREAD

**Issue by ritatsousa** [IBCNServices/pyRDF2Vec#1]
Hello, 
I am trying to reproduce the results from the RDF2Vec paper using your implementation. 
More specifically, I am using the generated embeddings for the AIFB dataset for classification with SVM, C4.5, Naive Bayes, and KNN.
However, I obtained results considerably different from the ones presented in RDF2Vec. 
Have you tried to reproduce the results? Is it possible that these differences can be due to differences in implementation?
Thanks

**Comment by GillesVandewiele** [comment]
Hi, 

Thanks for showing interest in this repository! What exactly are the results you are achieving? And which parameters are you exactly using? The depth of the walks, the dimension of the embedding and the number of walks extracted per walk can have quite an impact. I haven't looked that closely into exactly reproducing the numbers, but I think I did get quite good performances on both the AIFB and BGS dataset using this implementation.

**Comment by GillesVandewiele** [comment]
Also, it should perhaps be noted that there are also small difference between the results reported in the original paper, and from the paper of the authors of the relational graph CNNs

https://arxiv.org/pdf/1703.06103.pdf
and 
http://www.semantic-web-journal.net/system/files/swj1495.pdf

**Comment by GillesVandewiele** [comment]
Ok so I tried reproducing the results. I did notice a bug that when the max_walks_per_graph is set to float('inf') which should be equivalent to extracting all possible walks, then it gets stuck in an infinite loop somewhere which I will have a look at later.

I extracted 5000 walks per graph; no weisfeiler-lehman kernel; and all the rest default hyper-parameters, and obtained the following results:
```
Random Forest:
0.8055555555555556
[[13  1  1  0]
 [ 0  4  2  0]
 [ 2  0 10  0]
 [ 1  0  0  2]]
Support Vector Machine:
0.8333333333333334
[[13  1  1  0]
 [ 0  4  1  1]
 [ 1  0 11  0]
 [ 1  0  0  2]]
Gaussian Naive Bayes:
0.8611111111111112
[[12  1  2  0]
 [ 0  5  1  0]
 [ 1  0 11  0]
 [ 0  0  0  3]]
CART Decision Tree:
0.6666666666666666
[[12  1  1  1]
 [ 0  3  2  1]
 [ 1  2  8  1]
 [ 0  1  1  1]]
K-Nearest Neighbors:
0.8055555555555556
[[13  0  1  1]
 [ 0  5  1  0]
 [ 3  0  8  1]
 [ 0  0  0  3]]
```

Seems like most classifiers perform better, except the SVM which doesn't reach 90% at all and the decision tree which fails miserably (but it is CART (without post-pruning) which is a different algorithm than C4.5)
