### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Demirrr** [IBCNServices/pyRDF2Vec#11]
Hello,
Any thoughts ?

```
pip install pyRDF2Vec
Collecting pyRDF2Vec
Requirement already satisfied: scikit-learn in 
-------Installing collected packages: pyRDF2Vec
Successfully installed pyRDF2Vec-0.0.5

>>> from rdf2vec.converters import rdflib_to_kg
ModuleNotFoundError: No module named 'rdf2vec.converters'; 'rdf2vec' is not a package 
```

**Comment by GillesVandewiele** [comment]
Hi @Demirrr ,

Hard to say... Could you make sure that your script & directory are not called rdf2vec?

**Comment by Demirrr** [comment]
> Hi @Demirrr ,
> 
> Hard to say... Could you make sure that your script & directory are not called rdf2vec?

changing the script name did the trick :)

Cheers

**Comment by GillesVandewiele** [comment]
Great :ok_hand:
