### ISSUE TITLE
how to integrate pyRDF2Vec and pytorch_geometric

### ISSUE THREAD

**Issue by LangDaoAI** [IBCNServices/pyRDF2Vec#152]
Hi,

Great work for RDF GNN！

I want to ask how to how to integrate pyRDF2Vec and pytorch_geometric?  Or, any intersection between pyRDF2Vec and pytorch_geometric ?

pytorch_geometric: https://github.com/pyg-team/pytorch_geometric

Thanks!

**Comment by GillesVandewiele** [comment]
It looks like it is possible to integrate similar techniques into the pytorch_geometric framework indeed: https://antoniolonga.github.io/Pytorch_geometric_tutorials/posts/post10.html

**Comment by LangDaoAI** [comment]
> It looks like it is possible to integrate similar techniques into the pytorch_geometric framework indeed: https://antoniolonga.github.io/Pytorch_geometric_tutorials/posts/post10.html

@GillesVandewiele great sugguestion, thanks!

**Comment by LangDaoAI** [comment]
I also found

![image](https://user-images.githubusercontent.com/83859417/195545430-f582ba0c-0307-4bbc-bbe6-ccc1c3d5aa1a.png)

is a great answer of the reason why creating RDF2Vec
