### ISSUE TITLE
pyRDF2Vec implements RDF2vec light?

### ISSUE THREAD

**Issue by LangDaoAI** [IBCNServices/pyRDF2Vec#153]
Hi,

Another question : pyRDF2Vec implements RDF2vec light?

I read the following:

![image](https://user-images.githubusercontent.com/83859417/195553500-2ea0ab46-ca4d-4b37-ba69-9d9f7b59e328.png)

Thanks!

**Comment by GillesVandewiele** [comment]
According to rdf2vec.org:
```
RDF2vec Light is a variant of RDF2vec which addresses this trade off differently. It takes a predefined list of entities and computes embedding vectors only for those entities.
```

So yes, we do, since you need to provide a list of entities for which you want to generate embeddings to `fit()`

**Comment by LangDaoAI** [comment]
> According to rdf2vec.org:
> 
> ```
> RDF2vec Light is a variant of RDF2vec which addresses this trade off differently. It takes a predefined list of entities and computes embedding vectors only for those entities.
> ```
> 
> So yes, we do, since you need to provide a list of entities for which you want to generate embeddings to `fit()`

Thanks!  I see
