### ISSUE TITLE
Code from Getting Started does not work

### ISSUE THREAD

**Issue by bottledmind** [IBCNServices/pyRDF2Vec#172]
## 🐛 Bug
The code from Getting Started fails due to having 2 dependencies not installed and gensin Word2Vec having no `epochs` keyword

## Expected Behavior

Provided in the Getting Started section

## Current Behavior
```
ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-3-7470aa2fab00>](https://localhost:8080/#) in <module>
      1 import pandas as pd
      2 
----> 3 from pyrdf2vec import RDF2VecTransformer
      4 from pyrdf2vec.embedders import Word2Vec
      5 from pyrdf2vec.graphs import KG

[/usr/local/lib/python3.8/dist-packages/pyrdf2vec/__init__.py](https://localhost:8080/#) in <module>
----> 1 import nest_asyncio
      2 
      3 from .rdf2vec import RDF2VecTransformer
      4 
      5 # bypass the asyncio.run error for the Notebooks.

ModuleNotFoundError: No module named 'nest_asyncio'
```
```
ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-5-7470aa2fab00>](https://localhost:8080/#) in <module>
      1 import pandas as pd
      2 
----> 3 from pyrdf2vec import RDF2VecTransformer
      4 from pyrdf2vec.embedders import Word2Vec
      5 from pyrdf2vec.graphs import KG

3 frames

[/usr/local/lib/python3.8/dist-packages/pyrdf2vec/graphs/kg.py](https://localhost:8080/#) in <module>
      7 import attr
      8 import numpy as np
----> 9 import rdflib
     10 from cachetools import Cache, TTLCache, cachedmethod
     11 from cachetools.keys import hashkey

ModuleNotFoundError: No module named 'rdflib'
```
```
TypeError                                 Traceback (most recent call last)

[<ipython-input-7-7470aa2fab00>](https://localhost:8080/#) in <module>
     30 # Create our transformer, setting the embedding & walking strategy.
     31 transformer = RDF2VecTransformer(
---> 32     Word2Vec(epochs=10),
     33     walkers=[RandomWalker(4, 10, with_reverse=False, n_jobs=2)],
     34     # verbose=1

[/usr/local/lib/python3.8/dist-packages/pyrdf2vec/embedders/word2vec.py](https://localhost:8080/#) in __init__(self, **kwargs)
     32             **kwargs,
     33         }
---> 34         self._model = W2V(**self.kwargs)
     35 
     36     def fit(

TypeError: __init__() got an unexpected keyword argument 'epochs'
```

## Steps to Reproduce

1. Use Google Colaboratory
2. `pip install pyRDF2vec`
3. Running the code from Getting Started
4. `ModuleNotFoundError: No module named 'nest_asyncio'`
5. `pip install nest_asyncio`
6. `ModuleNotFoundError: No module named 'rdflib'`
7. `pip install rdflib`
8. `TypeError: __init__() got an unexpected keyword argument 'epochs'`

## Environment

- **Operating system:** Ubuntu 20.04.5 LTS
- **pyRDF2Vec version:** 0.2.3
- **Python version:** 3.8.10

**Comment by GillesVandewiele** [comment]
Hi,

Thank you for your interest in pyRDF2Vec. You will need to install nest_asyncio and rdflib through pip (which you have done), it seems like they are not included in the requirements.txt; something we will need to update!

With regards to error 8. I am a little bit clueless. mutag.py from examples/, which uses the epochs keyword, seems to run with python3.8 on my system:

```
gilles@gilles-NH5x-7xDCx-DDx:~/Projects/debug/test/pyRDF2Vec$ python3.8 examples/mutag.py 
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:01<00:00, 173.29it/s]
Extracted 48475 walks for 320 entities (2.0627s)
Fitted 48475 walks (1.8669s)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:00<00:00, 929.30it/s]
Extracted 320 literals for 320 entities (0.3446s)
Predicted 68 entities with an accuracy of 76.4706%
Confusion Matrix ([[TN, FP], [FN, TP]]):
[[43  2]
 [14  9]]
```

which version of gensim do you have installed?

**Comment by bottledmind** [comment]
It's a basic colab environment. All the non-default packages are mentioned above. 
gensim==3.6.0

**Comment by GillesVandewiele** [comment]
Can you try upgrading gensim to 4.0+? Breaking changes (including changing the keyword max_iter to epochs) were then introduced.

**Comment by enridaga** [comment]
Hi, I am having the same problem while reproducing the example on Google Colab:
```
TypeError: __init__() got an unexpected keyword argument 'epochs'
```
removing the argument seems sufficient to make it work.

**Comment by GillesVandewiele** [comment]
Yes, that is because the default version for gensim in colab is 3.6.0

![Screenshot from 2023-02-10 15-03-54](https://user-images.githubusercontent.com/5750603/218099094-fb00d7fc-897d-4268-8527-e6c457f94acc.png)

If you upgrade gensim to 4.0+ it works.

![Screenshot from 2023-02-10 15-04-17](https://user-images.githubusercontent.com/5750603/218099142-44253b15-e602-45b2-b8f2-6951b89f54a5.png)

![Screenshot from 2023-02-10 15-04-30](https://user-images.githubusercontent.com/5750603/218099196-d30c7990-14c8-455e-9e4a-3cd12db53451.png)

**Comment by enridaga** [comment]
That explains, thanks!
