### ISSUE TITLE
FUNCTION MOST SIMILAR 

### ISSUE THREAD

**Issue by STALINFIGUEROAALAVA** [IBCNServices/pyRDF2Vec#199]
## ❓ Question
Dear Bram and Guilles. I need to use the function most.similar with pyrdf2vec.
I would like to know if pyrdf2vec has this function and how the syntax would be

**Comment by bsteenwi** [comment]
Here's an example of how you can calculate cosine similarity using the scipy library in Python:

```
from scipy.spatial.distance import cosine

# example of an rdf2vec embedding
embedding1 = [0.1, 0.2, 0.5, 0.3]

# example of another rdf2vec embedding
embedding2 = [0.15, 0.25, 0.45, 0.35]

similarity = 1 - cosine(embedding1, embedding2)
print(similarity)
```

The cosine similarity ranges from -1 to 1, with 1 indicating identical embeddings and -1 indicating completely dissimilar embeddings.

You can iterate through your list of embeddings and compare each embedding with a reference embedding to find the most similar one based on your chosen similarity measure (as cosine similarity is only one of the options).

**Comment by STALINFIGUEROAALAVA** [comment]
Ok Bram Thaks very much.
