### ISSUE TITLE
why always no module named 'walkers'

### ISSUE THREAD

**Issue by Gigi-Yang** [IBCNServices/pyRDF2Vec#2]
??????????????????????????

**Comment by GillesVandewiele** [comment]
Hi Gigi,

Could you perhaps show us the error? It does not find the walkers module I guess? Did you use `pip install` or the `setup.py` script?

Try experimenting with different stuff:
Replace `import walkers` -> `import rdf2vec.walkers`

Or:
```
import sys
sys.path.append('PATH_OF_RDF2VEC_ON_YOUR_COMPUTER')
```

**Comment by Gigi-Yang** [comment]
is now a keyerror, but i install all modules it needs.

**Comment by GillesVandewiele** [comment]
Please paste the error you are having, so I can help you out. There did seem to be a bug with the CommunityWalker. Let me push a fix for that.

**Comment by Gigi-Yang** [comment]
`Traceback (most recent call last):
  File "Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a85b7ab5d0f2>", line 1, in <module>
    runfile('pyRDF2Vec-master/rdf2vec/example.py', wdir='pyRDF2Vec-master/rdf2vec')
  File "C:\Program Files\JetBrains\PyCharm 2019.2.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "pyRDF2Vec-master/rdf2vec/example.py", line 72, in <module>
    wl_embeddings = transformer.fit_transform(kg, train_people + test_people)
  File "pyRDF2Vec-master\rdf2vec\rdf2vec.py", line 150, in fit_transform
    self.fit(graph, instances)
  File "pyRDF2Vec-master\rdf2vec\rdf2vec.py", line 93, in fit
    all_walks += list(walker.extract(graph, instances))
  File "pyRDF2Vec-master\rdf2vec\walkers\community.py", line 90, in extract
    self._community_detection(graph)
  File "pyRDF2Vec-master\rdf2vec\walkers\community.py", line 46, in _community_detection
    self.communities[vertices[node]] = partition[node]
KeyError: '0.17'
`

**Comment by GillesVandewiele** [comment]
Ok, could you try pulling the newest version I pushed a few seconds ago? The error should be fixed :)

**Comment by Gigi-Yang** [comment]
It's OK. so where is the bug?

**Comment by Gigi-Yang** [comment]
It's OK. so where is the bug?

**Comment by Gigi-Yang** [comment]
It's OK. so where is the bug?

**Comment by GillesVandewiele** [comment]
:raised_hands: The bug had to do with how `Literals` currently being handled, I made a refactor for those in `graph.py`, but forgot to test if all the walkers still worked (which apparently was not the case). 

The fix was minimal: https://github.com/IBCNServices/pyRDF2Vec/commit/9cfaebda3b012044e512a0fe58e905e261930ae4

**Comment by Gigi-Yang** [comment]
Thank you for helping me

**Comment by GillesVandewiele** [comment]
Most welcome. Best of luck with using the library!

Just out of interest: for what use case are you using RDF2Vec?

**Comment by Gigi-Yang** [comment]
I am a student majoring in big data

**Comment by GillesVandewiele** [comment]
OK cool, and what kind of project are you currently doing? Or is it in the context of a thesis?

**Comment by Gigi-Yang** [comment]
OMG, it's my homework
