### ISSUE TITLE
Rename rdf2vec to pyrdf2vec

### ISSUE THREAD

**Issue by rememberYou** [IBCNServices/pyRDF2Vec#22]
The main folder of pyRDF2Vec is named `rdf2vec`. To my knowledge, this has never been a problem since the publication of this package was done manually. However, after the integration of [poetry](https://python-poetry.org/) for more easily manage our dependencies and the Python packaging, this solution is no longer possible.

Indeed, `poetry`, defined in the [pyproject.toml](https://github.com/IBCNServices/pyRDF2Vec/blob/master/pyproject.toml) file (according to [PEP 518](https://www.python.org/dev/peps/pep-0518/#id25)) is based on the `name` attribute which defines the folder (currently `rdf2vec`) that contains the source code of pyRDF2Vec, **which must also** be the name of the package that should be published.

**Source:** https://python-poetry.org/docs/cli/#publish

Therefore I propose to rename the `rdf2vec` main folder to `pyrdf2vec`. Such a change will slow down the writing of imports, I prefer to discuss this before committing such a change.

@GillesVandewiele should we rename this `rdf2vec` folder and rename the imports (_e.g.,_ `from rdf2vec.converters import endpoint_to_kg` to `from pyrdf2vec.converters import endpoint_to_kg`) or continue to publish pyRDF2Vec on PyPi "by hand" for future versions of pyRDF2Vec?

**Comment by GillesVandewiele** [comment]
Hi Terencio,

I agree with your proposal. I prefer renaming `rdf2vec` folder to `pyrdf2vec` as opposed to renaming the project to RDF2Vec. This mainly to distinguish ourselves from the original implementation and the rdf2vec.org website. 

The more we can automate, the better :)

**Comment by rememberYou** [comment]
Perfect, I will refactor this! :-)
