### ISSUE TITLE
generate embeddings from txt file 

### ISSUE THREAD

**Issue by halimaaol** [IBCNServices/pyRDF2Vec#221]
## ❓ Question

HI,
I want to generate embeddings for a dataset in FB15k  from a txt file using pyrdf2vec. Should I create the KG from scratch, or is there another way?

**Comment by GillesVandewiele** [comment]
You can convert the txt file to any RDF format and then use the "vanilla" KG class here.

**Comment by halimaaol** [comment]
thank you , 
I've converted the txt file to RDF format ,the "vanilla" KG you mean the 3rd method("from scratch")?

**Comment by GillesVandewiele** [comment]
No, method 2 (read RDF file with rdflib). Let me know if it works!

**Comment by halimaaol** [comment]
I use the 2nd method  :
kg=KG('graph.xml', fmt='xml') 
And when I tried to generate embedding with this code 
embeddings= transformer1.fit_transform(kg, enitites)    (where entities is list of entities in the graph)
I got an error :
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-159-60b4e6a23d9d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 embeddings= transformer1.fit_transform(kg,entities)
      2 

1 frames
[/usr/local/lib/python3.10/dist-packages/pyrdf2vec/rdf2vec.py](https://localhost:8080/#) in get_walks(self, kg, entities)
    164             if kg.mul_req:
    165                 asyncio.run(kg.connector.close())
--> 166             raise ValueError(
    167                 "At least one provided entity does not exist in the "
    168                 + "Knowledge Graph."

ValueError: At least one provided entity does not exist in the Knowledge Graph.

And I'm sure that the list of entities is included in the graph. How can I resolve this issue?

**Comment by GillesVandewiele** [comment]
IIRC, the entities have to be of type rdflib.URIRef

**Comment by halimaaol** [comment]
I got the same error when I change the type of entities to rdflib.URIRef

**Comment by GillesVandewiele** [comment]
Can you share a **minimal** code snippet & dataset so that I can reproduce?

**Comment by halimaaol** [comment]
yes , the dataset is from [https://github.com/villmow/datasets_knowledge_embedding](https://github.com/villmow/datasets_knowledge_embedding)
I started to create rdf graph:

 `graph=Graph()
  with open("dataset_name.txt", "r") as file:

    for line in file:
        parts = line.strip().split()
        if len(parts) == 3:
            entity1, relation, entity2 = parts

            entity1_uri = URIRef(f"{entity1}")
            entity2_uri = URIRef(f"{entity2}")
            relation_uri = URIRef(f"{relation}")
            graph.add((entity1_uri, relation_uri, entity2_uri))
            graph.serialize("fb15k.rdf", format="turtle")`

then I created the KG
 `from pyrdf2vec.graphs import KG
kg=KG('/content/fb15k.rdf',fmt="turtle")`

I create list of entities that are included in KG ,and I tried to generate embedding with : 

`transformer= RDF2VecTransformer(
    Word2Vec(epochs=10,vector_size=500),
    walkers=[RandomWalker(2, 40, with_reverse=False, n_jobs=4)],
    # verbose=1
) 
embeddings= transformer.fit_transform(kg,entities)`

thank you in advance

**Comment by GillesVandewiele** [comment]
Could you share the list of entities? And have you tried running it with only a few entities of which you are sure they are present in the graph?

**Comment by halimaaol** [comment]
yes sure, this the list of entities that I am sure the entities exist in knowledge graph:

`entities=['/m/05s34b','/m/0ddcbd5','/m/03ww_x','/m/07pzc','/m/0l3cy','/m/04l5d0','/m/0s5cg','/m/035nm','/m/0yx1m',
'/m/03nymk','/m/01jpmpv','/m/067nv','/m/01lhdt','/m/01jkqfz']`

**Comment by GillesVandewiele** [comment]
I fixed it. I did the following.

1) I take a look where in pyRDF2Vec this error is raised, which after some "jump to definition" I can find out this check is important: `return all([Vertex(entity) in self._vertices for entity in entities])`
2) So clearly, the entities in your list are not in the `kg._vertices`. That's weird since indeed, the entities you list can just be CTRL+F'ed in one of the files and found.
3) Doing a simple print of `list(kg._vertices)[:5]` shows that rdflib adds `file://` as a prefix to every URIRef if you don't define a namespace. You could have checked this yourself by just looking into the file you write to disk (`/content/fb15k.rdf`)
![image](https://github.com/IBCNServices/pyRDF2Vec/assets/5750603/e85b5479-64b2-4b8b-9aae-ffe489f33676)
4) Prepending `file://` to all my entities fixes the issue.
![image](https://github.com/IBCNServices/pyRDF2Vec/assets/5750603/85a50f95-caa6-414a-9edb-4eaac71e42bb)

**Comment by halimaaol** [comment]
Thank you for your help. 
I have just tried running the code, and it takes a considerable amount of time to generate a few embeddings. What if I use this code instead of the previous one?, is it a true way?
`from pyrdf2vec.graphs import KG`
`kg=KG('/content/fb15k.rdf',fmt="turtle")`
`kg._is_remote = True`

generate embeddings:

`entities=['/m/05s34b','/m/0ddcbd5','/m/03ww_x','/m/07pzc','/m/0l3cy','/m/04l5d0','/m/0s5cg','/m/035nm','/m/0yx1m', 
   '/m/03nymk','/m/01jpmpv','/m/067nv','/m/01lhdt','/m/01jkqfz']`

` embeddings= transformer.fit_transform(kg,entities)`

**Comment by GillesVandewiele** [comment]
is_remote is when you want to use a server, this will always be slower than working in memory and is only used when your KG is too large to fit in your memory.

How does your walker look like? Are you extracting all walks exhaustively or a fixed number of walks per entity? Whats the depth of your walks? There's many factors that influence how long it'll take. How long is it taking?
