### ISSUE TITLE
Gensim verson

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#243]
## ❓ Question
Hi,i whould know  what is the gension version used in Pyrdf2vec  0.2.3 
Thanks

**Comment by rememberYou** [comment]
Hi,

pyRDF2Vec will use `gensim 4.3.2` which is the latest version released at the moment.

As `gensim = "^4.0.1"` is specified in the `pyproject.toml` file, it allows installing any version of `gensim` within the range >=4.0.1 and <5.0.0
