### ISSUE TITLE
Set Parameters 

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#244]
## ❓ hi .

I whould ask how to set  PYTHONHASHSEED when i use  pyrdf2vec ..is it =40? .. and  exisit other IDE parameters to set when we use pyrdf2vec ?

 Thanks

**Comment by rememberYou** [comment]
Hi @nnadine25 , please check this issue about how to use random seeds: https://github.com/IBCNServices/pyRDF2Vec/issues/179

As far as I know, there are not IDE parameters for the random seed. You (just) need to run the script with an extra argument.
