### ISSUE TITLE
Store and save rdf2vec transformers

### ISSUE THREAD

**Issue by GillesVandewiele** [IBCNServices/pyRDF2Vec#27]
## 🚀 Feature
It should be possible to easily serialize our RDF2VecTransformer. A `load()` and `save()` method should be created. This can probably be done with `pickle`.

**Comment by rememberYou** [comment]
@GillesVandewiele can I close this issue based on [this implementation](https://github.com/IBCNServices/pyRDF2Vec/blob/1208024790076f1890802117e78ec6c05c5a72fb/pyrdf2vec/rdf2vec.py#L119) or do you see other things to implement with `pickle` in the immediate future?

**Comment by nirajdpandey** [comment]
This save and load [function at this line](https://github.com/IBCNServices/pyRDF2Vec/blob/1208024790076f1890802117e78ec6c05c5a72fb/pyrdf2vec/rdf2vec.py#L119) doesn't work. by manually dumping embedding by pickle is fine but then if one uses the provided way to load it it fails. 

```.py
with open('embd.bin', 'wb') as f:
  pickle.dump(walk_embeddings, f)

with open('embd.bin', "rb") as f:
    transformer = pickle.load(f)
    if not isinstance(transformer, RDF2VecTransformer):
        raise ValueError("Failed to load the RDF2VecTransformer object")`
```
`Returns: `#### ValueError: Failed to load the RDF2VecTransformer object

Also, is there any way to use such an embedding to find most similar match given an entity. Like we have with Gensim word2vec most_similar() function? to pyRFD2VEC support anything like that? Thanks in advance.

**Comment by GillesVandewiele** [comment]
Hi @nirajdpandey,

Thank you for reporting and for your interest in pyRDF2Vec.

In the code snippet you provide, is `walk_embeddings` an RDF2VecTransformer object? It seems (based on the name) more like a numpy array?

There is not a way to do this with our API, but one could quickly create a distance matrix of cosine distances between each pair of embedded entities. If you then want the nearest neighbor, you can take the corresponding row and get the embedding with minimal value. [scipy.cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) could help here.

**Comment by nirajdpandey** [comment]
Hi @GillesVandewiele , Thanks a lot for such nice work you have done. Actually I am following your blog on [this site](https://towardsdatascience.com/how-to-create-representations-of-entities-in-a-knowledge-graph-using-pyrdf2vec-82e44dad1a0) I am dumping and loading the same `walk_embedding` that you have mentioned in the blog. 

Actually my goal is to find similar entities in two knowledge graphs and thought of using your work. But it seems that it might not be very good in entity alignment task. What you think? I would really appreciate your help. thanks.

**Comment by GillesVandewiele** [comment]
Finding similar entities is definitely possible with cosine distances. I do that in this notebook: https://www.kaggle.com/group16/covid-19-knowledge-graph-embeddings (Application 2).

Can you elaborate on "entity alignment"? What's that?

**Comment by nirajdpandey** [comment]
Thanks again for the guidance. Well, `Entity alignment` seeks to find entities in different knowledge graphs (KGs) that refer to the same object.  The goal is to identify entities from different KGs that refer to the same entity, e.g. `Mount_Everest` in DBpedia  and `Q513` in Wikidata. I am struggling to find any simple approaches here. I thought maybe using embedding I can look for the most close entity given a search term. However, it's not very promising idea it seems. Do you have any suggestions to offer? I would appreciate it.

**Comment by GillesVandewiele** [comment]
Well, since pyRDF2Vec gives you **unsupervised** embeddings of the entities, you can use them for any downstream task. So that includes the entity alignment. I am not very familiar with the problem you describe, but it could probably be solved with some kind ranking. You need to create pairs of entities that refer to the same object (positive samples) and pairs of entities that refer to different objects (negative samples).

**Comment by rememberYou** [comment]
@GillesVandewiele can we close this issue or should we implement a better way to store and save RDF2Vec transformers than using the `pickle` module?

**Comment by GillesVandewiele** [comment]
We do need tests for that before we close!

**Comment by rememberYou** [comment]
You are right, we will wait the merge of the `develop` branch before close this issue.

https://github.com/IBCNServices/pyRDF2Vec/blob/98c4139160f5c01d46954e67055c5fa17d28c3b5/tests/test_rdf2vec.py#L56

**Comment by rememberYou** [comment]
Fixed by https://github.com/IBCNServices/pyRDF2Vec/commit/7f5d7301ab8a0c00fe53f2feedcb9680414cca2a
