### ISSUE TITLE
Improve user-friendliness of API

### ISSUE THREAD

**Issue by GillesVandewiele** [IBCNServices/pyRDF2Vec#29]
When `is_remote=False` is passed to `KG(...)` we should check with `os` library if the first argument is an existing file. This avoids users mixing up `is_remote=True` and `is_remote=False` usage.

Additionally, one could check if the provided URI is valid when `is_remote=True`

**Comment by rememberYou** [comment]
Fixed by https://github.com/IBCNServices/pyRDF2Vec/commit/08689623d5b550464ebb696d91b0eca23908e5b2
