### ISSUE TITLE
Using Wikidata Sparql Endpoint

### ISSUE THREAD

**Issue by krewer** [IBCNServices/pyRDF2Vec#30]
## ❓ Question

Hi,
we want to create embeddings for Items from DBpedia and Wikidata using sparql endpoints.

DBpedia works as expected:
kg = KG("https://dbpedia.org/sparql", is_remote=True)
we get fine results

Wikidata 
kg = KG("https://query.wikidata.org/sparql", is_remote=True)
edited kg.py to define and add agent in SPARQL Wrapper: self.endpoint = SPARQLWrapper(location, agent=user_agent)
we get results, but they seem to be random numbers, no clusters are recognizable in any way.
Checking against not existing URIs also leads to similar results -> Therefore we assume that with correct URIs there is also no real processing.

Is there something special to take care on when working with wikidata-sparql-endpoint?

BG werner

**Comment by GillesVandewiele** [comment]
Hi there,

Thank you for showing interest in pyRDF2Vec, and great to hear that you are already making your own modifications to the code base to suit your use case. We appreciate any kind of feedback on how we could make it easier for people to make these modifications!

How many walks are you extracting for each of the entities? Could you perhaps also print out the walks after extraction to take a look if that went well? A point in the code where you could print these walks is around this line: https://github.com/IBCNServices/pyRDF2Vec/blob/master/pyrdf2vec/rdf2vec.py#L72

**Comment by bsteenwi** [comment]
The DBPedia endpoint is based on Virtuoso (which provides the /sparql option).
Most of the wikidata queries are just concatenations of the query string to the following URL:https://query.wikidata.org/
So I'm not sure if this /sparql is needed for wikidata?

Example:
`https://query.wikidata.org/#SELECT%20%3Fp%20%3Fo%0AWHERE%0A%7B%0A%20%20wd%3AQ83894%20%3Fp%20%3Fo.%0A%7D`

**Comment by krewer** [comment]
Thanks to both for responding so quick.
@GillesVandewiele  your answer brought me to a new idea how to verify if there is a useful response from wikidata - and there is!  i have concentrated to less on what happens but on how the results are
I have to refine Walking Strategy and to define a better set of label_predicates to improve the quality of embeddings.

@bsteenwi thanks for the idea. i could now verify that "https://query.wikidata.org/sparql" works

**Comment by GillesVandewiele** [comment]
Hi @krewer, this could indeed help! It's also important to note that our remote KG is typically very slow when you have to query a server over the web, due to the many HTTP requests. Having your own local server would speed this is up significantly. As a result of the remote KG being so slow, a very low number of walks typically must be extracted in order to have results in a timely manner. Unfortunately, those results are often not that great with a low number of walks...

It is on our roadmap to optimize the efficiency of our remote KG!

**Comment by nnadine25** [comment]
Hi,
i also try to use Alternative 2: Using a dbpedia endpoint (nothing is loaded into memory)but it give me the this erros Extracted 0 walks for 0 entities! raise RuntimeError("you must first build vocabulary before training the model") RuntimeError: you must first build vocabulary before training the model
I
how does it work with sparql and dbpedia?using sparql property path  construct query  and rdflib ? where we put the query ?

**Comment by GillesVandewiele** [comment]
Hi @nnadine25 

Can we see the code you are using in order to help you debug? It should work by just providing the URL of the endpoint and then a list of entities (URIs/URLs) for which you want to generate embeddings. pyRDF2Vec will perform SPARQL queries under the hood:
```
SELECT ?p, ?o WHERE {
   <entity> ?p ?o.
}
```

With `<entity>` one of the provided URLs in your list.

**Comment by nnadine25** [comment]
thank you sir , so we don't need to create a sparql query ,  alsp as you says entity : one of the provided url ie we can create embeddings for categories witch contain 'Category ' in  the pattern http://dbpedia.org/resource/Category not only for dbpedia ressource ??

**Comment by GillesVandewiele** [comment]
I do not understand your question. Please re-phrase.

**Comment by nnadine25** [comment]
i.e with  rdf2vec we can create embeddings for also dbpedia categories not only entities and property ?

**Comment by GillesVandewiele** [comment]
Yes. You should be able to provide any URI that can be found at the endpoint you provided.

**Comment by nnadine25** [comment]
thanks sir , i have another question : when we use word2vec sometimes give differents values  or the same item(s) and we need to Ensure the gensim generate the same Word2Vec model for different runs on the same data, is it the same in rdf2vec ? the values in embedddings array are the same in each execusion ?

**Comment by GillesVandewiele** [comment]
See our README:

```
For a more elaborate example, check at the example.py file:

PYTHONHASHSEED=42 python3 example.py

NOTE: the PYTHONHASHSEED (e.g., 42) is to ensure determinism.
```

**Comment by nnadine25** [comment]
thank you , i have tried the simple example in  this page ; https://github.com/IBCNServices/pyRDF2Vec/wiki/Fast-generation-of-RDF2Vec-embeddings-with-a-SPARQL-endpoint
 but it take  long time for executing even for only one ressource as provided entity

**Comment by nnadine25** [comment]
and how to save the rdf2vec embeddings  ?

**Comment by nnadine25** [comment]
i dosent find the example page  it give me  empty page https://github.com/IBCNServices/pyRDF2Vec/blob/master/example.py 
i.e i need to set PYTHONHASHSEED=42 in pycharm?

**Comment by nnadine25** [comment]
i try this code and the values in numpy array are different in each execusion , i set the PYTHONHASHSEED=0 in pycharm

from pyrdf2vec.graphs import KG
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker
from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec
entities = ['<http://dbpedia.org/resource/Ralf_Schumacher>','<http://dbpedia.org/resource/Mick_Schumacher>']

kg = KG(location="https://dbpedia.org/sparql", is_remote=True)

walkers = [RandomWalker(1, 200, UniformSampler())]
embedder = Word2Vec(size=200)
transformer = RDF2VecTransformer(walkers=walkers, embedder=embedder)

embeddings = transformer.fit_transform(kg, entities)
print(embeddings)

i can't understand the problem ?

**Comment by nnadine25** [comment]
i try this code and it give me diffferent results in each execusion , i set the PYTHONHASHSEED=0 in pycharm

from pyrdf2vec.graphs import KG

import numpy as np
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker
from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec
entities = ['<http://dbpedia.org/resource/Ralf_Schumacher>','<http://dbpedia.org/resource/Mick_Schumacher>']

kg = KG(location="https://dbpedia.org/sparql", is_remote=True)

walkers = [RandomWalker(1, 200, UniformSampler())]
embedder = Word2Vec(size=200)
transformer = RDF2VecTransformer(walkers=walkers, embedder=embedder)

embeddings = transformer.fit_transform(kg, entities)
print(embeddings)

vector1=embeddings[0]
vector2=embeddings[1]

unit_vector_1 = vector1 / np.linalg.norm(vector1)
unit_vector_2 = vector2 / np.linalg.norm(vector2)
dot_product = np.dot(unit_vector_2, unit_vector_2)
print(dot_product)

**Comment by bsteenwi** [comment]
Hi,

To get reproducible embeddings, you have to set the PYTHONHASHSEED=0 as already discussed by Gilles.
You can set it in Pycharm as Environment Variable  (more info [here](https://stackoverflow.com/questions/60913405/how-to-set-pythonhashseed-environment-variable-in-pycharm-for-testing-word2vec-m))

But you also have to fix the sampler randomness
After you import numpy, add the following code:
```
np.random.seed(0)
```
This will ensure the np.random calls in our code are seeded.

We will add this information to our readme.

**Comment by rememberYou** [comment]
Thanks @bsteenwi, I added the explanation in the `README.rst` file of the `develop` branch.

**Link:** https://github.com/IBCNServices/pyRDF2Vec/tree/develop#how-to-ensure-the-generation-of-similar-embeddings

When the unit tests are all successful, I will make sure to do the merge.

**Comment by nnadine25** [comment]
thank you very much , i have another question  if we need to same the rdf2vec into a file , there is any specific extension  that the  file should be ?

**Comment by rememberYou** [comment]
If you are using version `pyRDF2Vec 0.1.1`, the library does not yet provide a function to save the `RDF2VecTransformer` object which contains the entity embeddings, but nothing prevents you from serializing the object yourself as explained below.

If you use a clone directly from the `master` branch of `pyRDF2Vec`, the `RDF2VecTransformer` object is saved and loaded by a binary file (`transformer_data` by default) using the `save` and `load` function.

**SEE:** https://github.com/IBCNServices/pyRDF2Vec/blob/8181e02a866bf274d50d66f28f1ffa7100ebb9a6/pyrdf2vec/rdf2vec.py#L119

Here is an easy to use example :
```python
RDF2VecTransformer(walkers=[RandomWalker(2, None)]).save("foo")
transformer = RDF2VecTransformer.load("foo")
```

Please create another issue if you still have other questions.

**Comment by nnadine25** [comment]
thank you , i will do , but the  values of embedddings array are stil  differents in each execusion  even when i set PYTHONHASHSEED=0  in pycharm and np.random.seed(0)

**Comment by rememberYou** [comment]
@nnadine25 Could you paste your current code with the modifications made? Use triple backticks following by `python` to paste your code here.

**SEE:** https://docs.github.com/en/enterprise-server@2.20/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by nnadine25** [comment]
i try the code in this page https://github.com/IBCNServices/pyRDF2Vec/wiki/Fast-generation-of-RDF2Vec-embeddings-with-a-SPARQL-endpoint
the values of the array differt in each execusion
from pyrdf2vec.graphs import KG
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker
from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec

kg = KG(location="http://YOUR_STARDOG_IP_OR_LOCALHOST:5820/dbpedia/query", is_remote=True)

walkers = [RandomWalker(1, 200, UniformSampler())]
embedder = Word2Vec(size=200)
transformer = RDF2VecTransformer(walkers=walkers, embedder=embedder)

embeddings = transformer.fit_transform(kg, ['http://dbpedia.org/resource/Brussels'])
print(embeddings)

**Comment by nnadine25** [comment]
i try the code in this page and the values of the array are different in each execusion even when set PYTHONHASHSEED=0 

the page : https://github.com/IBCNServices/pyRDF2Vec/wiki/Fast-generation-of-RDF2Vec-embeddings-with-a-SPARQL-endpoint

the example:

from pyrdf2vec.graphs import KG
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker
from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec

kg = KG(location="http://dbpedia.org/sparql", is_remote=True)

walkers = [RandomWalker(1, 200, UniformSampler())]
embedder = Word2Vec(size=200)
transformer = RDF2VecTransformer(walkers=walkers, embedder=embedder)

embeddings = transformer.fit_transform(kg, ['http://dbpedia.org/resource/Brussels'])
print(embeddings)

**Comment by GillesVandewiele** [comment]
There's no np.random.seed in that code...

**Comment by rememberYou** [comment]
@nnadine25 Use `pyRDF2Vec 0.1.1`: 
```bash
pip install pyRDF2Vec
```

The `master` branch uses new features such as multi processing and indeed in this case I don't get the same generation of embeddings (good to know), I will check it out why.

By using this code and saving it in a file(e.g., `foo.py`):

```python
import random

import numpy as np

from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec
from pyrdf2vec.graphs import KG
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker

# Ensure the determinism of this script by initializing a pseudo-random number
# generator.
np.random.seed(42)
random.seed(42)

transformer = RDF2VecTransformer(
    Word2Vec(size=200), walkers=[RandomWalker(1, 200)]
)

embeddings = transformer.fit_transform(
    KG(location="http://dbpedia.org/sparql", is_remote=True),
    ["http://dbpedia.org/resource/Brussels"],
)

with open("output.txt", "w") as f:
    for element in embeddings:
        f.write(str(element))
        f.write("\n")
```

I always get the same embeddings by executing the script like this:
```bash
PYTHONHASHSEED=42 python foo.py
```

Let me know if the problem persists.

**Comment by rememberYou** [comment]
A quick update after my analysis this morning. For the `master` branch, random determinism works well when you don't use multi processing (i.e. use the n-jobs parameter >=2 for Walker) which is still in test version. This is good to know. However, @nnadine25 I always have the same embeddings with your code.

**Comment by nnadine25** [comment]
thank you, i'm trying to run the program but it take so many time for execusion in pycharm unlike other scripts that run normally  , is it the same  problem in your IDE ?

**Comment by nnadine25** [comment]
thank you sir , but the problem always persists, i used the same code and the values in the arry are differents in each execusion , i used  the same code with PYTHONHASHSEED=42, the vaues in the arry sometimes begin with 2. and sometimes with 9 and other times with negatives numbers , i can't fount why this happen for me  i used (Word2Vec(size=200), [RandomWalker(1, 200)]) and i have only one entity

**Comment by nnadine25** [comment]
the values of the embeddings arrays are 
[array([ 9.05681809e-04, -2.38214445e-04, -1.27735408e-03,  1.20846683e-03,
       -5.43911410e-05,  1.35629834e-03, -5.35588733e-05, -1.07713661e-03,
       -1.44261250e-03, -2.00803485e-03,  1.03473000e-03, -3.32267373e-04,
        1.17934844e-03, -9.14518023e-04, -1.33650296e-03, -2.14917527e-04,
       -1.89128055e-04, -2.50192266e-03,  2.64411303e-03, -2.18469324e-03,
        2.43760296e-03,  1.71352539e-03,  5.30064863e-04, -1.95899466e-03,
       -2.24644202e-03, -3.50047572e-04,  1.75271393e-03,  2.29764660e-03,
        3.66455555e-04,  5.65962924e-04,  1.98883377e-03,  2.64073210e-03,
        3.64908658e-04, -2.00180686e-04,  1.34852645e-03, -1.38461380e-03,
       -2.34807190e-03,  2.14726594e-03,  1.05531735e-03,  1.59104809e-03,
        3.09802010e-04, -5.94904472e-04,  1.76208129e-03, -1.29727065e-03,
       -6.10092771e-04, -1.17188354e-03,  6.39035599e-04, -4.62652330e-04,
        1.05300837e-03, -1.82394462e-03, -1.91397418e-03,  2.51471740e-03,
       -2.49338191e-04,  1.13704766e-04,  1.21738599e-03,  6.14371675e-04,
        2.69668899e-03, -1.66596286e-03, -3.71912502e-05,  1.37544319e-03,
       -1.45398057e-03,  6.90579007e-04,  2.11162982e-03, -2.09564972e-03,
       -1.12308003e-03,  1.69006072e-03,  1.19462155e-03,  5.10179787e-04,
        1.01364532e-03,  2.51946924e-03, -1.88915711e-03,  1.13319529e-05,
        3.03130550e-03,  2.87303678e-03, -6.67612825e-04,  2.37894850e-03,
        1.87922269e-03, -1.17394712e-03,  1.11244572e-03, -1.01052318e-03,
        2.49384524e-04, -2.11963619e-04, -1.70608365e-03, -2.10169330e-03,
        1.92701386e-03,  6.50577247e-04,  1.08340255e-03, -2.64801225e-03,
        5.51396166e-04,  1.92860374e-03, -2.75092269e-03,  4.87663550e-04,
       -6.06824760e-05, -1.56729331e-03,  6.47210167e-04,  8.25846742e-04,
        1.48523657e-03, -1.46027177e-03, -1.86068739e-03, -1.30194786e-03,
       -2.27173720e-03,  9.84522165e-04, -3.97492811e-04,  8.72404780e-04,
       -8.74388861e-05, -1.58938463e-03, -2.48773536e-03, -1.25771156e-03,
        2.60760658e-03, -2.05055508e-03, -2.03984859e-03, -1.36582379e-03,
       -1.09966786e-03, -1.90278410e-03, -1.17804063e-03, -2.78219930e-03,
       -2.14722846e-03, -9.46414773e-04, -6.75538264e-04, -1.50975026e-03,
        2.06957292e-03, -2.52245436e-03,  1.89920378e-04, -1.36241096e-03,
       -2.41640210e-03,  1.94193621e-03, -4.45974001e-04,  4.77617607e-04,
        6.10001443e-04, -2.23656581e-03,  8.44506663e-04,  4.28159663e-04,
        1.11438136e-03,  2.86350754e-04,  1.37298997e-03, -2.09126296e-03,
       -1.15633965e-03,  1.25720561e-03,  1.58067804e-03,  8.72454315e-04,
        1.23090140e-04,  1.23399007e-03, -3.82249564e-04,  2.06533982e-03,
        1.21040526e-03, -2.52827560e-03, -2.57108733e-03, -1.03811896e-03,
        6.33939810e-04,  5.64003247e-04, -1.99222472e-03,  2.50269752e-03,
       -2.44230637e-03,  2.05184519e-03,  2.36870511e-03, -8.67906376e-04,
        1.49023219e-03,  1.38931675e-03, -4.25542894e-05,  2.09611128e-04,
        2.21578361e-04, -1.29577133e-03, -7.64687313e-04,  9.71853791e-04,
        2.13996085e-04,  7.85136246e-04,  1.00760965e-03, -1.27569179e-03,
       -1.42672891e-03,  9.81515477e-05, -2.24790466e-03,  1.12828391e-03,
        2.08723848e-03, -5.06813521e-04,  2.44584726e-03,  3.62575403e-04,
       -9.96484654e-04, -7.95337430e-04,  2.51923804e-03,  1.50565652e-03,
        2.47826264e-03,  8.59450229e-05,  1.62744673e-03, -2.09698197e-03,
        1.29826611e-03, -7.53670989e-04, -1.10121653e-03,  2.19665607e-03,
       -1.77367323e-03,  1.06509496e-03, -2.49752752e-03,  1.87777984e-03,
        1.47657597e-03,  1.69571990e-03, -3.15133162e-04, -2.19753874e-03,
        7.73929758e-04, -1.05317589e-03,  7.65046629e-04,  7.66520505e-04],
      dtype=float32)]
