### ISSUE TITLE
Advice about walkers using inbound and outbound links

### ISSUE THREAD

**Issue by moissinac** [IBCNServices/pyRDF2Vec#35]
Hello

I'm working to adapt our previous works to pyRdf2Vec. So, we need to build walks which are following in and out links of a vertex.
I see two possibilities:
* enhance the graph by building the reverse links (it's only possible for local graph)
* build a method similar to get_hops which add the inbound links to the outbound links obtained by get_hops (for exemple, by building hops with virtuel reverse predicates)
Could you give me some advices for the choice between the solutions and for the implementation of the second one (which is my favorite). I imagine that I need to use the _transition_matrix of the KG.

**Comment by GillesVandewiele** [comment]
Hi @moissinac,

I guess there are two options to take, depending on whether or not you use local or remote KGs.

If you use a local KG, I would suggest exactly what you proposed: extend your rdf file with inverse relations. For every (s, p, o) add (o, p', s) with p' the "inverse predicate of p"

If you use a remote KG, I think you best modify https://github.com/IBCNServices/pyRDF2Vec/blob/master/pyrdf2vec/graphs/kg.py#L92 to not only query (s, p, o) but also query (o, p, s) with a known `s`. get_shops returns the possible neighbors it can reach from a certain node. In your situation, this is the union of ingoing and outgoing edges.


The most elegant solution, if you do not want to modify your RDF file, would probably to create your own custom `Walker` object.

**Comment by moissinac** [comment]
Thank's for your quick reply
I'm checking if adding the following lines to a variant of get_hops makes sense
`        predicates = self._inv_transition_matrix[vertex]
        for pred in predicates:
            assert len(self._inv_transition_matrix[pred]) == 1
            for obj in self._inv_transition_matrix[pred]:
                hops.append((self.invPredicate(pred), obj))
`
where the invPredicate method build a 'virtual' predicate from the direct one

**Comment by GillesVandewiele** [comment]
Yes, that seems very correct a first glance! Of course there will be some trivial walks in there that might need to be filtered out (A -> B -> A -> B -> ...).

I think it would be nice to actually build this in as a functionality of pyRDF2Vec if possible. Often, the direction of these predicates is rather arbitrarily determined and one could argue to drop the entire directed aspect of a graph. Would you be willing to make a PR of the changes you have done?

**Comment by moissinac** [comment]
OK 
As soon as well checked

**Comment by moissinac** [comment]
Hello, I think I need to do my PR on a specific branch and I have no right to create one. Could you suggest a brach for the PR? Thanks

**Comment by GillesVandewiele** [comment]
Hi @moissinac 

You can make a clone of this repository, then work in your own created branch and then you can create a PR from there (you can do it through the github web client by just going to your cloned repo & branch and merging from there).

**Comment by GillesVandewiele** [comment]
Correction: fork the repo, don't clone :)
