### ISSUE TITLE
Refactor equality check

### ISSUE THREAD

**Issue by GillesVandewiele** [IBCNServices/pyRDF2Vec#36]
Replace checking of hashes by just equality checking the properties, as that is faster.

https://github.com/IBCNServices/pyRDF2Vec/blob/470d1a6167163b37787e251b610a91627a5d667a/pyrdf2vec/graphs/kg.py#L26

**Comment by rememberYou** [comment]
Fixed https://github.com/IBCNServices/pyRDF2Vec/commit/d6115d919f5b9a2394100628a5f283171e73cbd2
