### ISSUE TITLE
error when upgrade pyrdf2vec package

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#40]
hi, when i upgrade  rdf2vec to version 2.0 when i  work with this version i get the error 
Traceback (most recent call last):
 
    import pyrdf2vec
  File "C:\Users\ILINE\PycharmProjects\test2best\venv\lib\site-packages\pyrdf2vec\__init__.py", line 1, in <module>
    import nest_asyncio

ModuleNotFoundError: No module named 'nest_asyncio'

**Comment by GillesVandewiele** [comment]
Hi @nnadine25 

How did you install the latest version? In case you are cloning from GitHub, do not forget to run `poetry install` or `pip install .`

If you are installing from pip (`pip install pyrdf2vec`), dependencies should be automatically installed. If not, we will fix this!

**Comment by rememberYou** [comment]
By scripts, here is the right way to use pyRDF2Vec using `poetry` as dependency manager:
  ```sh
  pip install poetry
  git clone https://github.com/IBCNServices/pyRDF2Vec.git
  cd pyRDF2Vec
  poetry install
  poetry shell
  ```
However, when you use Jupyter or Google Collab Notebook, the `poetry shell` command that allows you to open a shell in your virtual environment does not work as it seems to. Probably, because a notebook doesn't need to use a virtual environment.

To bypass these errors on the Notebook, I recommend you to install the missing packages with `pip`:
```sh
!pip install aiohttp
!pip install nest-asyncio
!pip install rdflib
```

**Comment by nnadine25** [comment]
i use pycharm ide and i install pyrdf2vec using pip install only

**Comment by rememberYou** [comment]
Good point, ``nest-asyncio` is a packet defined in the `dev` section instead of being global:
https://github.com/IBCNServices/pyRDF2Vec/blob/592014bbcf3881b03cc8b807fc8ea1b6a56caeae/pyproject.toml#L68

I will patch this.

**Comment by nnadine25** [comment]
i installed the trre modules
!pip install aiohttp
!pip install nest-asyncio
!pip install rdflib
 and i still get theise error 
raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>

**Comment by rememberYou** [comment]
@nnadine25 I created the `0.2.1` release to fix this issue with `nest-asyncio`: https://pypi.org/project/pyrdf2vec/

Please, try again with `pyRDF2Vec 0.2.1`:
```sh
pip install pyrdf2vec
```

**Comment by nnadine25** [comment]
i tried this version 0.2.1 and i always get this message in the console
raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>

**Comment by GillesVandewiele** [comment]
That error seems to be related to using multiprocessing on Windows. Have you tried what the error is suggesting? I.e. putting your main script in this specific block:

```
if __name__ == '__main__':
  <PUT YOUR CODE HERE>
```

**Comment by nnadine25** [comment]
i do what you the message say and pyrd2vec new version 0.2.1 work weel thank you 

but i whould to know if the problem of random  of word2vec is fixed 
i try to find the embedding of the ressource in this example , and the aray found in changed in each execusion i found diffrents values of array 

import numpy as np
from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec
from pyrdf2vec.graphs import KG
from pyrdf2vec.samplers import UniformSampler
from pyrdf2vec.walkers import RandomWalker
import random
import multiprocessing

# Ensure the determinism of this script by initializing a pseudo-random number
# generator.
np.random.seed(42)
random.seed(42)

if __name__ == '__main__':
    transformer = RDF2VecTransformer(Word2Vec(workers=1, size=200), [RandomWalker(1, 200)])
    embeddings = transformer.fit_transform( KG(location="http://dbpedia.org/sparql", is_remote=True),
    ["http://dbpedia.org/resource/Brussels"] )
    print(embeddings)

**Comment by GillesVandewiele** [comment]
Ok great.

Yes, the problem of randomness has been completely fixed. You can ensure determinism by setting the seeds in the code as you have done:
```
np.random.seed(42)
random.seed(42)
```

But also by setting the PYTHONHASHSEED environment variable. I typically run my scripts from my command line `PYTHONHASHSEED=42 python3 my_awesome_script.py`

How to set this in your own environment is something you will have to Google yourself.

**Comment by nnadine25** [comment]
thank you i aldo  add  in  RandomWalker(2, None, random_state=42)
and i get the same ambeddings in each execusion 
tank you
