### ISSUE TITLE
meaning of the empty list at the end of the embeddings array

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#41]
hi ,
i whould ask what is meaning by the empty list at the end of the array([array([ 0.0083779 , -0.0097333 , -0.00225981, -0.01057816,  0.01266316,
       -0.00550285,  0.01651839, -0.00581943,  0.0165164 , -0.00847934,
       -0.02312157, -0.00571326,  0.00177471,  0.01618937,  0.00076064,
        0.00521333,  0.01502399,  0.0009116 , -0.01145697,  0.00365165,
       -0.00080776,  0.02441511, -0.00221602, -0.0119072 , -0.0165608 ,
        0.0101989 , -0.00139808,  0.02303413,  0.0048925 , -0.01682724,
        0.00453872,  0.00916675,  0.00147707, -0.00352545,  0.00403542,
        0.01361007, -0.00427693,  0.00124139,  0.0119957 , -0.01119698,
        0.00649284, -0.01733533,  0.00358338, -0.00396841,  0.00736378,
        0.00420047,  0.0108506 , -0.00380876, -0.01578493, -0.01183324,
       -0.00355217,  0.00925911,  0.01294927,  0.01107025,  0.00544836,
        0.005039  , -0.02145933, -0.01034022, -0.00858134,  0.01886703,
       -0.0054844 , -0.01462951, -0.00867096,  0.00334619, -0.00305369,
       -0.01331031,  0.00688533, -0.00967618,  0.01809203,  0.0203396 ,
       -0.00522942, -0.02041009, -0.00425156, -0.01385427,  0.01587442,
       -0.01395543, -0.00869405, -0.00107553,  0.00148736,  0.00621569,
        0.00596426, -0.01485674, -0.00726925,  0.0028231 ,  0.0276578 ,
        0.00896207,  0.0074825 ,  0.01189452, -0.00513235, -0.02138061,
       -0.00895545, -0.00870362,  0.00290429, -0.00532698,  0.00769983,
        0.02115051,  0.01662124,  0.01716363,  0.02318381, -0.0102157 ,
        0.00689081, -0.01348563,  0.00428424,  0.0139199 , -0.01293968,
        0.01977365, -0.00014994,  0.01049027, -0.01900207,  0.01211957,
        0.00123155,  0.0002017 ,  0.01996107,  0.0148954 ,  0.01931536,
        0.0134006 , -0.00888292,  0.01020645,  0.00096673, -0.00736072,
        0.01215172,  0.00483533, -0.00454102, -0.00157751, -0.01042432,
       -0.003007  , -0.00091393, -0.00382535, -0.00097798, -0.01381498,
       -0.01454435, -0.00110119,  0.00912866, -0.00777265, -0.00877869,
       -0.0049567 ,  0.00672327, -0.01213343, -0.01773899, -0.02463246,
       -0.00562515,  0.02292083, -0.00607371,  0.01005943, -0.01188215,
        0.00353662, -0.00287847,  0.00377765, -0.00202323, -0.00775664,
       -0.01295929,  0.01476607, -0.00485002, -0.006556  , -0.00177124,
       -0.02351536,  0.00686879,  0.00336398,  0.00947032,  0.01771237,
        0.0120958 ,  0.00209924,  0.01471658,  0.00743711, -0.01009965,
       -0.00039351, -0.01853843,  0.02391111, -0.00808878, -0.00091525,
       -0.01269393, -0.00656295,  0.01068002,  0.00037881,  0.00955251,
        0.01083717, -0.00241862, -0.00147978, -0.00854445,  0.00801867,
       -0.02087955, -0.00084609,  0.00977517,  0.0114574 ,  0.01317277,
        0.01666669,  0.0037135 , -0.00474095,  0.01407133, -0.02554555,
        0.00857792, -0.00794949, -0.01975685,  0.00501926,  0.00344069,
       -0.00242801,  0.00286963, -0.02595226, -0.01242554, -0.00199386],
      dtype=float32)], [])

**Comment by rememberYou** [comment]
Please make the effort to read the documentation of the functions you are using.

According to your question, I assume you called the `fit_transform` function of the `RDF2VecTransformer` class which returns which now not only returns a list of embeddings, but since version 0.2.0 also returns a list of literals. Therefore, this second empty list means that no literals were extracted because you didn't specify the predicate paths to follow for the extraction of these literals.

**Comment by bsteenwi** [comment]
More in general, as of version 0.2.0, we also provide some basic literal embedding support. We will provide a new blogpost in the future to show how this new feature works and how you can use it in your code.

For now, if you don't rely on this new feature, you can just neglect the empty list at the end.
