### ISSUE TITLE
prediction algorithms in rdf2vec

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#45]
hi , 
i whould ask what is the algorithm used in rdf2vec : cbow or skip-gram , and how we can change from an algorithm to another ?

**Comment by rememberYou** [comment]
RDF2Vec uses Word2Vec. Therefore, the use of CBOW or Skip-Gram is up to you, depending on your use case. The `pyRDF2Vec` library uses [gensim](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec)'s Word2Vec implementation which by default uses CBOW. However, you can use Skip-Grap by modifying the `sg` hyperparameter:
```python
from pyrdf2vec.embedders import Word2Vec

# To use CBOW (default behavior):
w2v = Word2Vec(sg=0)

# To use Skip-Gram:
w2v = Word2Vec(sg=1)
```

Refer to the appropriate documentation for more information.
