### ISSUE TITLE
embeddings of resource label 

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#49]
hi , 
i whould to  know if we can generate embeddings for the uri ressource label using pyrdf2vec in order to compare it with the embeddings array of a word using word2vec, or rdf2vec accept only uri ressources not rdfs:label ??

**Comment by rememberYou** [comment]
If your question is about the possibility to train Word2Vec using the `rdflib.term.URIRef` type to train your entities, the answer is "no" with the new version of pyRDF2Vec. 

When you initialize a local Knowledge Graph, the `KG` class convert each vertex in `str` type  which is stored in a `self._vertices` attribute, later used by the `RDF2VecTransformer` class to know if the provided training entities are present in the provided Knowledge Graph.

If you pass your training entities with a `rdflib.term.URIRef` type as parameter to the `RDF2VecTransformer`, this later will always return that the entities are not present in the provided Knowledge Graph, as these entities are not of the same type. Therefore, I recommend you convert the `rdflib.term.URIRef` to `str` using `str(uri)` or `uri.toPython()` functions.

**NOTE:** any pull request is welcome to allow good support for both types, but this is not the priority at the moment with pyRDF2Vec.

Finally, comparing a word embedding (e.g., Belgium) from Word2Vec with a pyRDF2Vec embedding for a resource (e.g., Belgium from DBpedia), makes no sense if you don't compare it against other relations (e.g., relation between Belgium and Brussels in the embedding space).
