### ISSUE TITLE
is pyrdf2vec consitant with  word2vec gensim 4.00

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#51]
## ❓ Question

hi, 
i whould ask if is pyrdf2vec consitant with  word2vec gensim 4.00 ? or there is any updates ?

**Comment by bsteenwi** [comment]
The latest pyRDF2Vec release uses gensim version 4.0.1
You can verify all package version information inside the [project config file](https://github.com/IBCNServices/pyRDF2Vec/blob/master/pyproject.toml)
