### ISSUE TITLE
literals when using categories embeddings 

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#53]
i try to get embeddings of categories not entities : i get the literal like this :
    categories =
 ['http://dbpedia.org/resource/Category:Climatology','http://dbpedia.org/resource/Category:Radiometry','http://dbpedia.org/resource/Category:Anarchism']

[[nan, nan], [nan, nan], [nan, nan]]

**Comment by rememberYou** [comment]
To extract the literals for the provided entities, you need to provide a list of predicate sequences that the walking strategy must follow to access these literals. I invite you to read the documentation and the [corresponding example](https://github.com/IBCNServices/pyRDF2Vec/blob/master/examples/literals.py)
