### ISSUE TITLE
pyrdf2vec version

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#54]
hi , 

i need to use gensim 3.8.2 in my code , i whould ask what is the pyrdf2vec version that is consistant with gensim 3.8.2 version?

**Comment by rememberYou** [comment]
The oldest version available on GitHub uses at least `gensim 3.8.3`. Therefore, I would clone `pyRDF2Vec 0.2.1` and change the dependencies manually in `pyproject.toml` to use `gensim 3.8.2` instead of `gensim 3.8.3`. There should be no problems.
