### ISSUE TITLE
pyredf2vec the new version

### ISSUE THREAD

**Issue by nnadine25** [IBCNServices/pyRDF2Vec#55]
## ❓ Question

hi , i whould ask if we need to use the random.seed() method of the random module , or numpy.random.seed()  to ensure determinist embedding in the new version of pyrdf2vec
thanks

**Comment by rememberYou** [comment]
The [FAQ](https://github.com/IBCNServices/pyRDF2Vec#how-to-ensure-the-generation-of-similar-embeddings) does not say so. So no.
