### ISSUE TITLE
Version 0.2.3 only extracts 1 walk per entity on notebook where multiple were extracted

### ISSUE THREAD

**Issue by GillesVandewiele** [IBCNServices/pyRDF2Vec#56]
https://www.kaggle.com/bsteenwi/rdf2vec extracts roughly 100K walks for 2000 entities (this was done with version 0.2.2). If we fork the notebook and run it today (version 0.2.3) we only get 2K walks (1 per entity).

**Comment by bsteenwi** [comment]
Hi Gilles, thank you for your interest in pyRDF2Vec!
The bug in this Kaggle example is not directly related to pyRDF2Vec, but more to this rdflib-hdt code line:
```
res = self.graph.query(query)
```
It throws an exception for all queries and, therefore, returns empty neighbourhoods.
We will adapt the example and make sure it works again.
