### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lbq8942** [IBCNServices/pyRDF2Vec#58]
is there  AIFB MUTAG BGS and AM dataset available?i need the rdf format.

![image](https://user-images.githubusercontent.com/64315774/145714134-e975ff4e-8251-4f05-ae1a-b62228d1e221.png)

**Comment by bsteenwi** [comment]
Hi, you can find those datasets here:

http://data.dws.informatik.uni-mannheim.de/rmlod/LOD_ML_Datasets/data/datasets/RDF_Datasets/

**Comment by lbq8942** [comment]
Got it,thank you so much.
