### ISSUE TITLE
rdf2vec version compatible with gensim 3.8.3

### ISSUE THREAD

**Issue by WafaNour** [IBCNServices/pyRDF2Vec#60]
Hi, 
i wan't to ask about pyrdf2vec version which is compatible with gensim 3.8.3 or older .
thank you

**Comment by rememberYou** [comment]
Hello,

[pyrdf2vec 0.2.1](https://github.com/IBCNServices/pyRDF2Vec/releases/tag/0.2.1) is compatible with `gensim 3.8.3`.

**SEE**:
https://github.com/IBCNServices/pyRDF2Vec/blob/a527c43fe1ad86bfe4f9e6a2398bd18c8e1619de/pyproject.toml#L46
https://github.com/IBCNServices/pyRDF2Vec/blob/a527c43fe1ad86bfe4f9e6a2398bd18c8e1619de/pyrdf2vec/embedders/word2vec.py#L20-L34
