### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by WarisBunglawala** [IBCNServices/pyRDF2Vec#64]
So, basically I want to use pyrdf2vec library for my personal project work but at first I wanted to try how it works, so for that I tried to install it in my PyCharm community addition 2021 and I tried to run the sample program that is mentioned in the GitHub documentation. 

now coming to the errors I am facing after installing the pyrdf2vec library first of all it is installed using the name rdf2vec instead of pyrdf2vec and that too without complete folders for example embedder, graphs and other few folders weren't there. for better understanding see the screenshot below.

![Screenshot (79)](https://user-images.githubusercontent.com/46418493/154828970-d296b639-e82c-4236-93b7-2e62f451c76b.png)

now coming to the code the exact sample code I have copy pasted in my editor which obviously throws error on no module name pyrdf2vec but as you can see that when I changed the pyrdf2vec to rdf2vec it is available (see line 2 for rdf2vec and see other lines for pyrdf2vec)  the code that i tried to run and explain errors in it is mentioned below.

```
import pandas as pd
from rdf2vec import RDF2VecTransformer # this line wont throw error
from pyrdf2vec.embedders import Word2Vec # all of these line will throw errors
from pyrdf2vec.graphs import KG
from pyrdf2vec.walkers import RandomWalker


# Read a CSV file containing the entities we want to classify.
data = pd.read_csv("samples/countries-cities/entities.tsv", sep="\t")
entities = [entity for entity in data["location"]]
print(entities)
# [
#    "http://dbpedia.org/resource/Belgium",
#    "http://dbpedia.org/resource/France",
#    "http://dbpedia.org/resource/Germany",
# ]

# Define our knowledge graph (here: DBPedia SPARQL endpoint).
knowledge_graph = KG(
    "https://dbpedia.org/sparql",
    skip_predicates={"www.w3.org/1999/02/22-rdf-syntax-ns#type"},
    literals=[
        [
            "http://dbpedia.org/ontology/wikiPageWikiLink",
            "http://www.w3.org/2004/02/skos/core#prefLabel",
        ],
        ["http://dbpedia.org/ontology/humanDevelopmentIndex"],
    ],
)
# Create our transformer, setting the embedding & walking strategy.
transformer = RDF2VecTransformer(
    Word2Vec(epochs=10),
    walkers=[RandomWalker(4, 10, with_reverse=False, n_jobs=2)],
    # verbose=1
)
# Get our embeddings.
embeddings, literals = transformer.fit_transform(knowledge_graph, entities)
print(embeddings)
# [
#     array([ 1.5737595e-04,  1.1333118e-03, -2.9838676e-04,  ..., -5.3064007e-04,
#             4.3192197e-04,  1.4529384e-03], dtype=float32),
#     array([-5.9027621e-04,  6.1689125e-04, -1.1987977e-03,  ...,  1.1066757e-03,
#            -1.0603866e-05,  6.6087965e-04], dtype=float32),
#     array([ 7.9996325e-04,  7.2907173e-04, -1.9482171e-04,  ...,  5.6251377e-04,
#             4.1435464e-04,  1.4478950e-04], dtype=float32)
# ]

print(literals)
# [
#     [('1830 establishments in Belgium', 'States and territories established in 1830',
#       'Western European countries', ..., 'Member states of the Organisation
#       internationale de la Francophonie', 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations'), 0.919],
#     [('Group of Eight nations', 'Southwestern European countries', '1792
#       establishments in Europe', ..., 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations', 'Transcontinental
#       countries'), 0.891]
#     [('Germany', 'Group of Eight nations', 'Articles containing video clips', ...,
#       'Member states of the European Union', 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations'), 0.939]
#  ]
```

Now due to incomplete library and folders from PyCharm download I tried to install it using commands mentioned in the documentation 

pip install pyRDF2vec

and now it is good to go according to me but as the sample file was not available in the package i manually download it and placed somewhere else in my pc and provided the path to it in the code which only change the line from the code

this:
```data = pd.read_csv("samples/countries-cities/entities.tsv", sep="\t")```

To this:
```data = pd.read_csv(r"C:\Users\Warisahmed\OneDrive\Desktop\gdb\samples\countries-cities\entities.tsv", sep="\t")```

and then i run my program which throws an error stating that 

```
C:\Users\Warisahmed\AppData\Local\Programs\Python\Python310\python.exe C:/Users/Warisahmed/PycharmProjects/KnowledgeGraph/n2v.py
['http://dbpedia.org/resource/Belgium', 'http://dbpedia.org/resource/France', 'http://dbpedia.org/resource/Germany', 'http://dbpedia.org/resource/Australia', 'http://dbpedia.org/resource/New_Zealand', 'http://dbpedia.org/resource/Peru', 'http://dbpedia.org/resource/Sri_Lanka', 'http://dbpedia.org/resource/Cyprus', 'http://dbpedia.org/resource/Spain', 'http://dbpedia.org/resource/Portugal', 'http://dbpedia.org/resource/Russia', 'http://dbpedia.org/resource/Brussels', 'http://dbpedia.org/resource/Paris', 'http://dbpedia.org/resource/Berlin', 'http://dbpedia.org/resource/Canberra', 'http://dbpedia.org/resource/Wellington', 'http://dbpedia.org/resource/Lima', 'http://dbpedia.org/resource/Nicosia', 'http://dbpedia.org/resource/Colombo', 'http://dbpedia.org/resource/Madrid', 'http://dbpedia.org/resource/Lisbon', 'http://dbpedia.org/resource/Moscow']
Traceback (most recent call last):
  File "C:\Users\Warisahmed\PycharmProjects\KnowledgeGraph\n2v.py", line 37, in <module>
    embeddings, literals = transformer.fit_transform(knowledge_graph, entities)
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\pyrdf2vec\rdf2vec.py", line 143, in fit_transform
    self.fit(self.get_walks(kg, entities), is_update)
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\pyrdf2vec\rdf2vec.py", line 163, in get_walks
    if kg.skip_verify is False and not kg.is_exist(entities):
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\pyrdf2vec\graphs\kg.py", line 374, in is_exist
    responses = [self.connector.fetch(query) for query in queries]
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\pyrdf2vec\graphs\kg.py", line 374, in <listcomp>
    responses = [self.connector.fetch(query) for query in queries]
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\cachetools\__init__.py", line 686, in wrapper
    return c[k]
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\cachetools\__init__.py", line 414, in __getitem__
    link = self.__getlink(key)
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\cachetools\__init__.py", line 501, in __getlink
    value = self.__links[key]
  File "C:\Users\Warisahmed\AppData\Roaming\Python\Python310\site-packages\cachetools\keys.py", line 19, in __hash__
    self.__hashvalue = hashvalue = hash(self)
TypeError: unhashable type: 'SPARQLConnector'

Process finished with exit code 1
```

i hope the issue i am facing is now clear to you and that is why i am unable to understand this issue. so can you explain now what should i do or doing wrong here.

Thank You.

**Comment by rememberYou** [comment]
Could you explain how you installed pyRDF2Vec and provide the snippet of code you would like to run?

**Comment by WarisBunglawala** [comment]
First of all i tried to install this lib using pycharm but it was throwing errors when i tried your sample code and the error was straight from the beginning that no such module available 
Then i tried diff diff methods but that didn't work due to some kind of naming errors such as pyRDF2Vec or pyrdf2vec all that 

Then i pull the whole repo using git and placed it in my project and installed ramaining dependencies then i tried your example which runs without throwing any other errors except the one i mentioned above 

The code is exactly the same as you provided i just changed the location of edges.tsv file so only the path has been changed nothing else.

`import pandas as pd

from pyrdf2vec import RDF2VecTransformer
from pyrdf2vec.embedders import Word2Vec
from pyrdf2vec.graphs import KG
from pyrdf2vec.walkers import RandomWalker

# Read a CSV file containing the entities we want to classify.
data = pd.read_csv("entities.tsv", sep="\t")
entities = [entity for entity in data["location"]]
print(entities)
# [
#    "http://dbpedia.org/resource/Belgium",
#    "http://dbpedia.org/resource/France",
#    "http://dbpedia.org/resource/Germany",
# ]

# Define our knowledge graph (here: DBPedia SPARQL endpoint).
knowledge_graph = KG(
    "https://dbpedia.org/sparql",
    skip_predicates={"www.w3.org/1999/02/22-rdf-syntax-ns#type"},
    literals=[
        [
            "http://dbpedia.org/ontology/wikiPageWikiLink",
            "http://www.w3.org/2004/02/skos/core#prefLabel",
        ],
        ["http://dbpedia.org/ontology/humanDevelopmentIndex"],
    ],
)
# Create our transformer, setting the embedding & walking strategy.
transformer = RDF2VecTransformer(
    Word2Vec(epochs=10),
    walkers=[RandomWalker(4, 10, with_reverse=False, n_jobs=2)],
    # verbose=1
)
# Get our embeddings.
embeddings, literals = transformer.fit_transform(knowledge_graph, entities)
print(embeddings)
# [
#     array([ 1.5737595e-04,  1.1333118e-03, -2.9838676e-04,  ..., -5.3064007e-04,
#             4.3192197e-04,  1.4529384e-03], dtype=float32),
#     array([-5.9027621e-04,  6.1689125e-04, -1.1987977e-03,  ...,  1.1066757e-03,
#            -1.0603866e-05,  6.6087965e-04], dtype=float32),
#     array([ 7.9996325e-04,  7.2907173e-04, -1.9482171e-04,  ...,  5.6251377e-04,
#             4.1435464e-04,  1.4478950e-04], dtype=float32)
# ]

print(literals)
# [
#     [('1830 establishments in Belgium', 'States and territories established in 1830',
#       'Western European countries', ..., 'Member states of the Organisation
#       internationale de la Francophonie', 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations'), 0.919],
#     [('Group of Eight nations', 'Southwestern European countries', '1792
#       establishments in Europe', ..., 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations', 'Transcontinental
#       countries'), 0.891]
#     [('Germany', 'Group of Eight nations', 'Articles containing video clips', ...,
#       'Member states of the European Union', 'Member states of the Union for the
#       Mediterranean', 'Member states of the United Nations'), 0.939]
#  ]`

**Comment by rememberYou** [comment]
Please make an effort in the writing if you want an answer that is clear and precise. You can start by wrapping your code via directly into the issue with three back ticks or via a parser. 

The [README (https://github.com/IBCNServices/pyRDF2Vec#installation)https://github.com/IBCNServices/pyRDF2Vec#installation) is quite clear for the installation of pyRDF2Vec. Make sure you install pyRDF2Vec either via `pip`, `poetry` or from source. Then you can test the import of pyRDF2Vec by opening a terminal and doing a simple import (e.g., `import pyrdf2vec`) if with this import you get an error, then the concern is in the package installation.

**Comment by WarisBunglawala** [comment]
I will rewrite the issue clearly after sometime ...my laptop is not with me and i have followed the installation process staight from the GitHub instructions but i faced lot of issues ...but as you said i will write clear and precise problem i am facing.

**Comment by WarisBunglawala** [comment]
i have updated the details please do check it out incase you did not get the notification. thank you

**Comment by rememberYou** [comment]
Thank you for taking the trouble to restructure your question. Unfortunately, I don't use PyCharm and these issues are not intended to begin to solve the problems of every IDE out there. Your issue is clearly not related to pyRDF2Vec

In this kind of situation you have three main solutions:
1. Install pyRDF2Vec as the standard recommends (with `pip`, `poetry` or via source), without using PyCharm.
2. Look on the web, why PyCharm renames pyRDF2Vec to rdf2vec and better understand the installation process of this IDE.
3. Use the docker-compose of the repository, in order to omit the installation of the dependencies.

Make sure to clean up the pyRDF2Vec installation that your IDE has done before anything else.

**Comment by rememberYou** [comment]
One last remark, the files present in sample must be accessible when you install pyRDF2Vec. If when you install pyRDF2Vec with pip, these files are missing, there is a problem with your `pip`.

You can see it by yourself, by [downloading manually the source code](https://github.com/IBCNServices/pyRDF2Vec/releases/tag/0.2.3) of the last release of pyRDF2Vec.

**Comment by WarisBunglawala** [comment]
i understand that you are not obligated to solve every IDE related problems sir 

but the main question i want to formed here is i have downloaded the pyrdf2vec using standard method of pip as i mentioned in my updated query 

and i run the program but that unhasable SPARQLConnector error was throwing after the pip installation and everything is find after pip installation.
so i think that could be the problem related to pyrdf2vec as i have only followed standard pip installation only.

**Comment by rememberYou** [comment]
Classes internal to pyRDF2Vec also use imports with the "pyRDF2vec" typeface. If PyCharm for some reason renames these imports to rdf2vec, it can only lead to errors of this kind.

For the installation with `pip`, make sure that the installation has been done and that there has not been any error due to a dependency version.

Try to see first if you can:
1. do a simple import of pyRDF2Vec into your terminal (with `import pyrdf2vec`)
2. run an example file (e.g., [mutag](https://github.com/IBCNServices/pyRDF2Vec/blob/master/examples/mutag.py)) with Python.

Can you confirm that this works?

If it works, you can try to interact with DBpedia via the [countries file](https://github.com/IBCNServices/pyRDF2Vec/blob/master/examples/countries.py) in the examples or via the snippet in the README.
