### ISSUE TITLE
Unclear error when using a TriplyDB endpoint

### ISSUE THREAD

**Issue by wouterbeek** [IBCNServices/pyRDF2Vec#69]
## 🐛 Bug

The code examples with DBpedia all work fine for me:

```py
knowledge_graph = KG("https://dbpedia.org/sparql")
```

But when I change the endpoint to a public TriplyDB endpoint:

```py
knowledge_graph = KG("https://api.triplydb.com/datasets/DBpedia-association/dbpedia/services/dbpedia/sparql")
```

I get the following error message:

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    knowledge_graph = KG("https://api.triplydb.com/datasets/DBpedia-association/dbpedia/services/dbpedia/sparql")
  File "<attrs generated init pyrdf2vec.graphs.kg.KG>", line 26, in __init__
  File "/home/wouter/.local/lib/python3.8/site-packages/attr/_make.py", line 3096, in __call__
    v(inst, attr, value)
  File "/home/wouter/.local/lib/python3.8/site-packages/pyrdf2vec/utils/validation.py", line 58, in _check_location
    raise ValueError(
ValueError: 'location' must be a valid URL (got https://api.triplydb.com/datasets/DBpedia-association/dbpedia/services/dbpedia/sparql)
```

This not seem to be a valid error message; after all the endpoint seems to be denoted by a valid URL.

## Expected Behavior

- Either a working RDF2Vec script,
- Or an error message that explains the actually issue.

## Current Behavior

An error message that claims that the specified URL is invalid.

## Steps to Reproduce

1. Use one of the example scripts that uses the DBpedia endpoint.
2. Replace the DBpedia URL with the above TriplyDB endpoint URL and run the script again.
3. Observe the above communicated error message.

## Environment

- **Operating system:** Ubuntu 20.04.4 LTS
- **pyRDF2Vec version:** 0.2.3
- **Python version:** 3.8.10

**Comment by rememberYou** [comment]
pyRDF2Vec considers an endpoint to be valid if it could receive an HTTP Status Code 200 (OK) after sending an HTTP Head request.

**Source:** https://github.com/IBCNServices/pyRDF2Vec/blob/6ec61421797514cac5e9cd45a08fb16206b91b37/pyrdf2vec/utils/validation.py#L94-L97

Unlike the DBpedia URL, the TriplyDB endpoint return a HTTP Status Code 400 (Bad Request) if we do not directly submitting a query:
```python
import requests
res = requests.head("https://api.triplydb.com/datasets/DBpedia-association/dbpedia/services/dbpedia/sparql").status_code
print(res) # 400
```
If I take another dataset, this request is considered invalid:
```python
import requests
endpoint = "https://api.triplydb.com/datasets/academy/pokemon/services/pokemon/sparql"
res = requests.get(endpoint, params={'format': 'json' }).status_code
print(res) # 400
```

And this one as being valid:
```python
import requests
endpoint = "https://api.triplydb.com/datasets/academy/pokemon/services/pokemon/sparql"
query = "SELECT * { ?s ?p ?o } LIMIT 1"
resp= requests.get(endpoint, params={'query': query, 'format': 'json' }).status_code
print(res) # 200
```

I see two issues to be addressed:
1. Modify the validity of a URL to check if we an HTTP Status Code 200 **or 400 (Bad Request)**.
2. Allow a user to interact with a private Knowledge Graph endpoint, by inviting him to specify his credentials during the requests.

**Comment by rememberYou** [comment]
Sending an empty query to test the validity of the URL would be even better. Thanks for the suggestion!

I did suggest that one could also interact with a private endpoint as this is probably a future issue that pyRDF2Vec user could have. In this case the validity of the URL would still be wrong with the current implementation. However, another separate issue would be more appropriate.

**Comment by rememberYou** [comment]
By setting the [is_valid_url](https://github.com/IBCNServices/pyRDF2Vec/blob/6ec61421797514cac5e9cd45a08fb16206b91b37/pyrdf2vec/utils/validation.py#L83-L99) function found in `pyrdf2vec/utils`, with the code below:

```python
def is_valid_url(url: str) -> bool:
    """Checks if a given URL is valid.

    Args:
        url: The URL to check the validity.

    Returns:
        True if the URL is valid, False otherwise.

    """
    try:
        query = "SELECT * { ?s ?p ?o } LIMIT 1"
        res = requests.head(
            url,
            params={'query': query},
            headers={"Accept": "text/html"}
        ).status_code
        return res == requests.codes.ok
    except Exception:
        return False
```

Are you now able to interact with TriplyDB without any issue?

**Comment by rememberYou** [comment]
@wouterbeek This [commit](https://github.com/IBCNServices/pyRDF2Vec/commit/e69110116f4865bf0702fd30f1fad2eea9895931) on the `develop` branch should fix this issue. Let us know if you still have any issue with TriplyDB.

**Comment by wouterbeek** [comment]
@rememberYou I think the commit indeed fixes my reported bug.  I'm not able to test this fully on my side because of #76.

**Comment by wouterbeek** [comment]
I was now able to test this in the develop branch.  Thanks for fixing this!

**Comment by rememberYou** [comment]
Thanks to you for reporting the issue.
