### ISSUE TITLE
What is the project's output?

### ISSUE THREAD

**Issue by Gigi-Yang** [IBCNServices/pyRDF2Vec#9]
The classification or other?

**Comment by GillesVandewiele** [comment]
Embeddings are the output of the `transform` method. If you specified the dimension to be 500 and you pass `K` entities to the `transform` method, then you will have a `Kx500` embedding matrix. In our `example.py` script, we use these embeddings for classification.

**Comment by Gigi-Yang** [comment]
em，and why rdf2vec is unsupervised technique, it may be self-supervised ??

**Comment by GillesVandewiele** [comment]
Because it does not use label information to create the embeddings. It will base its embedding on the neighborhood of an entity.
